// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx5KH4kZmZVZ85_16J509uPGxAUwMeu7E',
    appId: '1:41091466183:web:9bbb2fe30fa856f9288fe2',
    messagingSenderId: '41091466183',
    projectId: 'ai-health-coach-1558c',
    authDomain: 'ai-health-coach-1558c.firebaseapp.com',
    storageBucket: 'ai-health-coach-1558c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcVbaKxov5656K6yCmkwCRS9rb4sgCQA',
    appId: '1:41091466183:android:8f77c44a09965baa288fe2',
    messagingSenderId: '41091466183',
    projectId: 'ai-health-coach-1558c',
    storageBucket: 'ai-health-coach-1558c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ggXr72d71CqcpMW30iDXRQcWW_HYvCI',
    appId: '1:41091466183:ios:36bd6d2351ce8009288fe2',
    messagingSenderId: '41091466183',
    projectId: 'ai-health-coach-1558c',
    storageBucket: 'ai-health-coach-1558c.firebasestorage.app',
    iosBundleId: 'com.example.aiHealthCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ggXr72d71CqcpMW30iDXRQcWW_HYvCI',
    appId: '1:41091466183:ios:36bd6d2351ce8009288fe2',
    messagingSenderId: '41091466183',
    projectId: 'ai-health-coach-1558c',
    storageBucket: 'ai-health-coach-1558c.firebasestorage.app',
    iosBundleId: 'com.example.aiHealthCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx5KH4kZmZVZ85_16J509uPGxAUwMeu7E',
    appId: '1:41091466183:web:3a6d7ef6a2e6adb5288fe2',
    messagingSenderId: '41091466183',
    projectId: 'ai-health-coach-1558c',
    authDomain: 'ai-health-coach-1558c.firebaseapp.com',
    storageBucket: 'ai-health-coach-1558c.firebasestorage.app',
  );
}
